services:
    mysqldb:
        image: mysql
        container_name: mysqlcontainer
        command:
        #--default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
            - $HOME/database:/var/lib/mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: patientsdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: letmein
            MYSQL_ROOT_PASSWORD: letmein
            SERVICE_TAGS: dev
            SERVICE_NAME: mysqldb
        networks:
            - internalnet

networks:
    internalnet:
        driver: bridge
